services:
  postgres:
    image: postgres:16.1
    ports:
      - '${DOCKER_DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: $DOCKER_DATABASE_NAME
      POSTGRES_USER: $DOCKER_DATABASE_USERNAME
      POSTGRES_PASSWORD: $DOCKER_DATABASE_PASSWORD

  opensearch:
    image: opensearchproject/opensearch:1.2.0
    container_name: opensearch
    networks:
      - palolog
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      - discovery.type=single-node
      - 'OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g' # JVM 메모리 설정
      - TZ=Asia/Seoul
      - 'search.max_open_scroll_context=1000'
    healthcheck:
      test: ['CMD', 'curl', '-s', '-k', 'https://localhost:9200']
      interval: 30s
      timeout: 10s
      retries: 3

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash
    networks:
      - palolog
    ports:
      - '514:514/udp'
    environment:
      LS_JAVA_OPTS: '-Xms8g -Xmx8g'
      pipeline.batch.size: '15000'
      pipeline.workers: '8'
      pipeline.ecs_compatibility: disabled
      TZ: Asia/Seoul
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    command: logstash -f /usr/share/logstash/pipeline/logstash_11.0.conf

networks:
  palolog:
    driver: bridge
