export const dummy = [
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 3,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 4,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
  {
    time: 0,
    receiveTime: 0,
    serial: '-',
    hostid: '-',
    type: '-',
    subtype: '-',
    src: '-',
    dst: '-',
    natsrc: '-',
    natdst: '-',
    rule: '-',
    ruleUuid: '-',
    srcuser: '-',
    dstuser: '-',
    app: '-',
    zoneFrom: '-',
    zoneTo: '-',
    inboundIf: '-',
    outboundIf: '-',
    sessionid: '-',
    repeatcnt: 0,
    sport: '-',
    dport: '-',
    natsport: '-',
    natdport: '-',
    flags: '-',
    proto: '-',
    action: '-',
    misc: '-',
    threatid: '-',
    thrCategory: '-',
    severity: '-',
    direction: '-',
    bytes: 0,
    bytesSent: 0,
    bytesReceived: 0,
    packets: 0,
    pktsSent: 0,
    pktsReceived: 0,
    sessionEndReason: '-',
    deviceName: '-',
    eventid: '-',
    object: '-',
    module: '-',
    opaque: '-',
    srcloc: '-',
    dstloc: '-',
    urlIdx: '-',
    category: '-',
    urlCategoryList: '-',
    domainEdl: '-',
    reason: '-',
    justification: '-',
    subcategoryOfApp: '-',
    categoryOfApp: '-',
    technologyOfApp: '-',
    riskOfApp: '-',
    raw: '-',
  },
];

export interface IRow {
  time?: number | null | undefined;
  receiveTime?: number | null | undefined;
  serial?: string | null | undefined;
  hostid?: string | null | undefined;
  type?: string | null | undefined;
  subtype?: string | null | undefined;
  src?: string | null | undefined;
  dst?: string | null | undefined;
  natsrc?: string | null | undefined;
  natdst?: string | null | undefined;
  rule?: string | null | undefined;
  ruleUuid?: string | null | undefined;
  srcuser?: string | null | undefined;
  dstuser?: string | null | undefined;
  app?: string | null | undefined;
  zoneFrom?: string | null | undefined;
  zoneTo?: string | null | undefined;
  inboundIf?: string | null | undefined;
  outboundIf?: string | null | undefined;
  sessionid?: string | null | undefined;
  repeatcnt?: number | null | undefined;
  sport?: string | null | undefined;
  dport?: string | null | undefined;
  natsport?: string | null | undefined;
  natdport?: string | null | undefined;
  flags?: string | null | undefined;
  proto?: string | null | undefined;
  action?: string | null | undefined;
  misc?: string | null | undefined;
  threatid?: string | null | undefined;
  thrCategory?: string | null | undefined;
  severity?: string | null | undefined;
  direction?: string | null | undefined;
  bytes?: number | null | undefined;
  bytesSent?: number | null | undefined;
  bytesReceived?: number | null | undefined;
  packets?: number | null | undefined;
  pktsSent?: number | null | undefined;
  pktsReceived?: number | null | undefined;
  sessionEndReason?: string | null | undefined;
  deviceName?: string | null | undefined;
  eventid?: string | null | undefined;
  object?: string | null | undefined;
  module?: string | null | undefined;
  opaque?: string | null | undefined;
  srcloc?: string | null | undefined;
  dstloc?: string | null | undefined;
  urlIdx?: string | null | undefined;
  category?: string | null | undefined;
  urlCategoryList?: string | null | undefined;
  domainEdl?: string | null | undefined;
  reason?: string | null | undefined;
  justification?: string | null | undefined;
  subcategoryOfApp?: string | null | undefined;
  categoryOfApp?: string | null | undefined;
  technologyOfApp?: string | null | undefined;
  riskOfApp?: string | null | undefined;
  raw?: string | null | undefined;
}
