import { z } from 'zod';

export type zLogs = z.infer<ReturnType<typeof zPaloLogs>>;
export const zPaloLogs = () =>
  z.object({
    time: z.number().nullish(),
    receiveTime: z.number().nullish(),
    serial: z.string().nullish(),
    hostid: z.string().nullish(),
    type: z.string().nullish(),
    subtype: z.string().nullish(),
    src: z.string().nullish(),
    dst: z.string().nullish(),
    natsrc: z.string().nullish(),
    natdst: z.string().nullish(),
    rule: z.string().nullish(),
    ruleUuid: z.string().nullish(),
    srcuser: z.string().nullish(),
    dstuser: z.string().nullish(),
    app: z.string().nullish(),
    zoneFrom: z.string().nullish(),
    zoneTo: z.string().nullish(),
    inboundIf: z.string().nullish(),
    outboundIf: z.string().nullish(),
    sessionid: z.string().nullish(),
    repeatcnt: z.number().nullish(),
    sport: z.string().nullish(),
    dport: z.string().nullish(),
    natsport: z.string().nullish(),
    natdport: z.string().nullish(),
    flags: z.string().nullish(),
    proto: z.string().nullish(),
    action: z.string().nullish(),
    misc: z.string().nullish(),
    threatid: z.string().nullish(),
    thrCategory: z.string().nullish(),
    severity: z.string().nullish(),
    direction: z.string().nullish(),
    bytes: z.number().nullish(),
    bytesSent: z.number().nullish(),
    bytesReceived: z.number().nullish(),
    packets: z.number().nullish(),
    pktsSent: z.number().nullish(),
    pktsReceived: z.number().nullish(),
    sessionEndReason: z.string().nullish(),
    deviceName: z.string().nullish(),
    eventid: z.string().nullish(),
    object: z.string().nullish(),
    module: z.string().nullish(),
    opaque: z.string().nullish(),
    srcloc: z.string().nullish(),
    dstloc: z.string().nullish(),
    urlIdx: z.string().nullish(),
    category: z.string().nullish(),
    urlCategoryList: z.string().nullish(),
    domainEdl: z.string().nullish(),
    reason: z.string().nullish(),
    justification: z.string().nullish(),
    subcategoryOfApp: z.string().nullish(),
    categoryOfApp: z.string().nullish(),
    technologyOfApp: z.string().nullish(),
    riskOfApp: z.string().nullish(),
    raw: z.string().nullish(),
  });
